name: jaspr_icons_pack

description: A collection of svg icon for use in a jaspr app, easy to use and tree-shakable.

version: 1.0.2

license: MIT

repository: https://github.com/makanakidev/jaspr_icons_pack.git

issue_tracker: https://github.com/makanakidev/jaspr_icons_pack/issues

homepage: https://github.com/makanakidev/jaspr_icons_pack.git

topics:
  - jaspr
  - icon
  - svg
  - web

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  jaspr: ^0.22.4

dev_dependencies:
  lints: ^6.0.0
